twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/email_images': images
        '%kernel.project_dir%/public/css': email

when@test:
    twig:
        strict_variables: true

