### Liste des adresses
GET http://localhost:8080/api/address
### Détail d'une adresse
GET http://localhost:8080/api/address/3
### Ajout d'une adresse
POST http://localhost:8080/api/address/
content-type: application/json

{
    "street": "21 rue du test",
    "zipcode": "48000",
    "city":"Bazinga"
}
### Modification d'une adresse
PATCH http://localhost:8080/api/address/3
content-type: application/json

{
    "zipcode": "03000"
}
### Suppression d'une adresse
DELETE http://localhost:8080/api/address/4