### Liste des utilisateurs
GET http://localhost:8080/api/address
### Détail d'un utilisateur
GET http://localhost:8080/api/address/1
### Ajout d'un utilisateur
POST http://localhost:8080/api/address/
content-type: application/json

{
    "street": "Testaaa",
    "zipcode": "Test",
    "city":"Test",
    "department":"Test"
}
### Modification d'un utilisateur
PATCH http://localhost:8080/api/address/7
content-type: application/json

{
    "street": "24 rue du Matokopat",
    "city": "Pokomoto"
}
### Suppression d'un utilisateur
DELETE http://localhost:8080/api/address/20