### Liste des groupes
GET http://localhost:8080/api/band
### Détail d'un groupe
GET http://localhost:8080/api/band/1
### Ajout d'un groupe
POST http://localhost:8080/api/band/
content-type: application/json

{

}
### Modification d'un groupe
PATCH http://localhost:8080/api/band/7
content-type: application/json

{

}
### Suppression d'un groupe
DELETE http://localhost:8080/api/band/20