### Liste des groupes
GET http://localhost:8080/api/band
### Détail d'un groupe
GET http://localhost:8080/api/band/1
### Ajout d'un groupe
POST http://localhost:8080/api/band/
content-type: application/json

{
    "name": "Tesat",
    "description": "Test Band APIa",
    "area": 105,
    "sample": null,
    "picture": null,
    "users": [60],
        "address": {
            "street": "24 rue du Test Artiste",
            "zipcode": "99000",
            "city": "ArtisteCity"
        },
    "genres": [1],
    "tags": [1]
}

### Modification d'un groupe
PATCH http://localhost:8080/api/band/1
content-type: application/json

{
     "address": {
        "zipcode": "12000"
     }
}
### Suppression d'un groupe
DELETE http://localhost:8080/api/band/1