### Liste des événements
GET http://localhost:8080/api/event
### Détail d'un événement
GET http://localhost:8080/api/event/1
### Ajout d'un événement
POST http://localhost:8080/api/event/
content-type: application/json

{
    "field": "test"
}

### Modification d'un événement
PATCH http://localhost:8080/api/event/1
content-type: application/json

{
    "field": "test"
}
### Suppression d'un événement
DELETE http://localhost:8080/api/event/1