### Liste des adresses
GET http://localhost:8080/api/message/
### Détail d'une adresse
GET http://localhost:8080/api/message/3
### Ajout d'une adresse
POST http://localhost:8080/api/message/
content-type: application/json

{
    "sender":151,
    "recipient":160,
    "content":"TEST 2",
    "created_at":"2023/10/12"
    
}
### Modification d'une adresse
PATCH http://localhost:8080/api/message/3
content-type: application/json

{
    "content": "test du contenu"
}
### Suppression d'une adresse
DELETE http://localhost:8080/api/message/4