### Liste des organisateurs
GET http://localhost:8080/api/organizer

### Détail d'un organisateur
GET http://localhost:8080/api/organizer/61

### Ajout d'un organisateur
POST http://localhost:8080/api/organizer/
content-type: application/json

{
    "name": "Adressae test",
    "description": "Description",
    "email": "test@gmail.com",
    "users": [108],
    "type":  9,
    "address": {
      "street": "24 rue du test POST",
      "zipcode": "43000",
      "city": "TestLand"
    }
}
### Modification d'un organisateur
PATCH http://localhost:8080/api/organizer/58
content-type: application/json

{
    "name": "Hello"
}

### Suppression d'un organisateur
DELETE http://localhost:8080/api/organizer/26