### Liste des adresses
GET http://localhost:8080/api/address
### Détail d'une adresse
GET http://localhost:8080/api/address/1
### Ajout d'une adresse
POST http://localhost:8080/api/address/
content-type: application/json

{
    "street": "Testaaa",
    "zipcode": "Test",
    "city":"Test",
    "department":"Test"
}
### Modification d'une adresse
PATCH http://localhost:8080/api/address/7
content-type: application/json

{
    "street": "24 rue du Matokopat",
    "city": "Pokomoto"
}
### Suppression d'une adresse
DELETE http://localhost:8080/api/address/20