### Récupération du token
POST http://localhost:8080/api/login_check
content-type: application/json

{
    "username":"rojobaga@melodica.fr",
    "password":"admin"
}

### Liste des utilisateurs
GET http://localhost:8080/api/user

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk0NTM4MzAsImV4cCI6MTY5OTQ1NzQzMCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InJvam9iYWdhQG1lbG9kaWNhLmZyIn0.fG9gnzoHS461E-h2817kboS0wcSxIJ0795UcojbSGc1roA7O4YW2YCeXMSqhECr7H8v4oT6rbs8qTz4oFuqKVsc_gW9C5g7u3nlLAQ4sECTakzO6t_s00jxR9SXBuN0R3ID8yJg7GMIu9Bu73A3W7VyFVFgxQFh0k-4bA4mtjhde5AZP45yZH9Bqn_Pm1JhqojtykXr7N4idDpxBAuXlfE075Oe4TTAYmK-Wcd5zZNwDZADUuwg-dyhmEoCmirMVTb5Z8SVeMQecSu13lLnrh3KEEh4oIpWbyJK4LEyUlpEeUBZz5YSmvE0z2XiGEaJ4qFGsii6sS3kBoTauQhuehQ


### Détail d'un utilisateur
GET http://localhost:8080/api/user/2

### Ajout d'un utilisateur
POST http://localhost:8080/api/user/
content-type: application/json

{
    "firstname": "TestAPIaa",
    "lastname": "TestAPIaa",
    "birthday": "2023-10-26T00:00:00+02:00",
    "email": "testAPIaaaa@test.com",
    "password": "test",
    "phone_number": "0674896526",
    "picture": "test.png",
    "created_at": "2023-10-27T15:56:27+02:00"
}

### Modification d'un utilisateur
PATCH http://localhost:8080/api/user/2
content-type: application/json

{
    "firstname": "Testa"
}

### Suppression d'un utilisateur
DELETE http://localhost:8080/api/user/1